-- https://www.postgresql.org/docs/9.1/functions-string.html
-- select first_name || ' ' || last_name as full_name from customer;
-- select first_name, char_length(first_name) from customer;
-- select upper(first_name) from customer;